// Generated by CoffeeScript 1.6.1
(function() {
  var __slice = [].slice,
    _this = this,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.Gamescore = (function() {

    function Gamescore() {}

    Gamescore.value = 0;

    Gamescore.increment = 100;

    Gamescore.initialLives = 2;

    Gamescore.lives = Gamescore.initialLives;

    Gamescore.increment_value = function() {
      return this.value += this.increment;
    };

    return Gamescore;

  })();

  this.Utils = (function() {

    function Utils() {}

    Utils.addChainedAttributeAccessor = function(obj, attr) {
      return obj[attr] = function() {
        var newValues;
        newValues = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        if (newValues.length === 0) {
          return obj['_' + attr];
        } else {
          obj['_' + attr] = newValues[0];
          obj.image.attr(attr, obj['_' + attr]);
          return obj;
        }
      };
    };

    Utils.timestamp = function() {
      return new Date().getTime();
    };

    Utils.angle = function(a) {
      return 2 * Math.PI * a / 360;
    };

    Utils.path_seg = function(p) {
      var a;
      a = p.pathSegTypeAsLetter;
      switch (a) {
        case 'M':
        case 'm':
          return [a, p.x, p.y].join(" ");
        case 'L':
        case 'l':
          return [a, p.x, p.y].join(" ");
        case 'A':
        case 'a':
          return [a, p.r, p.r, p.rot, p.c, p.d, p.x, p.y].join(" ");
        case 'C':
        case 'c':
          return [a, p.x1, p.y1, p.x2, p.y2, p.x, p.y].join(" ");
        case 'S':
        case 's':
          return [a, p.x2, p.y2, p.x, p.y].join(" ");
        case 'Q':
        case 'q':
          return [a, p.x1, p.y1, p.x, p.y].join(" ");
        case 'T':
        case 't':
          return [a, p.x, p.y].join(" ");
        case 'Z':
        case 'z':
          return a;
      }
    };

    Utils.d = function(path) {
      var p;
      return ((function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = path.length; _i < _len; _i++) {
          p = path[_i];
          _results.push(this.path_seg(p));
        }
        return _results;
      }).call(this)).join(" ");
    };

    Utils.pathTween = function(d, i, a) {
      var interp, prec;
      prec = 4;
      interp = function(d, path) {
        var distances, dt, n0, n1, p, points;
        n0 = path.getTotalLength();
        p = path.cloneNode();
        p.setAttribute("d", d);
        n1 = p.getTotalLength();
        distances = [0];
        i = 0;
        dt = prec / Math.max(n0, n1);
        while ((i += dt) < 1) {
          distances.push(i);
        }
        distances.push(1);
        points = distances.map(function(t) {
          var p0, p1;
          p0 = path.getPointAtLength(t * n0);
          p1 = p.getPointAtLength(t * n1);
          return d3.interpolate([p0.x, p0.y], [p1.x, p1.y]);
        });
        return function(t) {
          if (t < 1) {
            return "M" + points.map(function(p) {
              return p(t);
            }).join("L");
          } else {
            return d;
          }
        };
      };
      return interp(d, this);
    };

    return Utils;

  })();

  this.Element = (function() {

    function Element(config) {
      var _this = this;
      this.config = config != null ? config : {};
      this.integrate = function() {
        return Element.prototype.integrate.apply(_this, arguments);
      };
      this.dt = this.config.dt || 0.4;
      this.r = this.config.r || new Vec();
      this.v = this.config.v || new Vec();
      this.f = this.config.f || new Vec();
      this.n = this.config.n || [];
      this.force = this.config.force || new Force();
      this.size = this.config.size || 0;
      this.go = this.config.go || false;
      this.react = this.config["true"] || true;
      this.tol = this.config.tol || 0.5;
      this.fixed = this.config.fixed || false;
      this._stroke = this.config.stroke || "none";
      this._fill = this.config.fill || "black";
      this.angle = this.config.angle || 0;
      this.is_root = this.config.is_root || false;
      this.is_bullet = this.config.is_bullet || false;
      this.type = this.config.type || null;
      this.image = this.config.image || null;
      this.g = d3.select("#game_g").append("g").attr("transform", "translate(" + this.r.x + "," + this.r.y + ")");
      this.g = this.config.g || this.g;
      this.svg = this.config.svg || d3.select("#game_svg");
      this.quadtree = this.config.quadtree || null;
      this.width = this.svg.attr("width");
      this.height = this.svg.attr("height");
      this.tick = 10;
      this.lasttick = Utils.timestamp();
      Utils.addChainedAttributeAccessor(this, 'fill');
      Utils.addChainedAttributeAccessor(this, 'stroke');
    }

    Element.prototype.collision_detect = function() {
      var size, x0, x3, y0, y3,
        _this = this;
      if (!(this.react && Collision.list.length > 0)) {
        return;
      }
      Collision.update_quadtree();
      size = Math.max(2 * this.size + this.tol, 50);
      x0 = this.r.x - size;
      x3 = this.r.x + size;
      y0 = this.r.y - size;
      y3 = this.r.y + size;
      return Collision.quadtree.visit(function(node, x1, y1, x2, y2) {
        var p;
        p = node.point;
        if (p !== null) {
          if (!(_this !== p.d && p.d.react)) {
            return false;
          }
          if ((p.x >= x0) && (p.x < x3) && (p.y >= y0) && (p.y < y3)) {
            Collision.check(_this, p.d);
          }
        }
        return x1 >= x3 || y1 >= y3 || x2 < x0 || y2 < y0;
      });
    };

    Element.prototype.reaction = function(n) {
      if (n == null) {
        n = void 0;
      }
      if (n != null) {
        return n.reaction();
      }
    };

    Element.prototype.integrate = function() {
      var f, r, timestamp;
      timestamp = Utils.timestamp();
      if (this.fixed || timestamp - this.lasttick <= this.tick) {
        return;
      }
      r = new Vec(this.r);
      f = this.force.f(r);
      this.r.add(new Vec(this.v).scale(this.dt)).add(new Vec(f).scale(0.5 * this.dt * this.dt));
      this.f = this.force.f(this.r);
      this.v.add(f.add(this.f).scale(0.5 * this.dt));
      this.lasttick = timestamp;
      if (r.x !== this.r.x || r.y !== this.r.y) {
        this.draw();
        this.collision_detect();
      }
      if (this.go) {

      } else {
        return true;
      }
    };

    Element.prototype.draw = function() {
      this.g.attr("transform", "translate(" + this.r.x + "," + this.r.y + ") rotate(" + (360 * 0.5 * this.angle / Math.PI) + ")");
    };

    Element.prototype.start = function(delay) {
      if (delay == null) {
        delay = null;
      }
      this.go = true;
      if (this.fixed) {
        return;
      }
      d3.timer(this.integrate, delay);
    };

    Element.prototype.stop = function() {
      this.go = false;
    };

    Element.prototype.deactivate = function() {
      this.react = false;
      this.fixed = true;
      this.stop();
    };

    Element.prototype.activate = function() {
      this.react = true;
      this.fixed = false;
      this.start();
    };

    Element.prototype.death_check = function(n) {
      if (this.is_root) {
        return n.death_check(this);
      }
      if (this.is_bullet) {
        return n.death_check(this);
      }
      return false;
    };

    Element.prototype.death = function() {
      this.deactivate();
      this.g.remove();
    };

    return Element;

  })();

  this.Game = (function() {

    function Game(config) {
      this.config = config != null ? config : {};
      this.element = [];
      this.svg = d3.select("#game_svg");
      this.g = d3.select("#game_g");
      this.width = this.svg.attr("width");
      this.height = this.svg.attr("height");
      this.scale = 1;
    }

    Game.prototype.init = function() {
      Collision.list = this.element;
      return Collision.update_quadtree();
    };

    Game.prototype.start = function() {
      var element, _i, _len, _ref, _results;
      _ref = this.element;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        element = _ref[_i];
        _results.push(element.start());
      }
      return _results;
    };

    Game.prototype.stop = function() {
      var element, _i, _len, _ref, _results;
      _ref = this.element;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        element = _ref[_i];
        _results.push(element.deactivate());
      }
      return _results;
    };

    return Game;

  })();

  this.Circle = (function(_super) {

    __extends(Circle, _super);

    function Circle(config) {
      this.config = config != null ? config : {};
      Circle.__super__.constructor.apply(this, arguments);
      this.type = 'Circle';
      this.size = 15;
      this.image = this.g.append("circle");
      this.image.attr("stroke", this._stroke);
      this.image.attr("fill", this._fill);
    }

    Circle.prototype.draw = function() {
      Circle.__super__.draw.apply(this, arguments);
      this.image.attr("r", this.size);
      if (this.r.x < 0 || this.r.x > this.width || this.r.y < 0 || this.r.y > this.height) {
        this.deactivate();
        return this.g.remove();
      }
    };

    return Circle;

  })(Element);

  this.Polygon = (function(_super) {

    __extends(Polygon, _super);

    function Polygon(config) {
      this.config = config != null ? config : {};
      Polygon.__super__.constructor.apply(this, arguments);
      this.type = 'Polygon';
      this.path = this.config.path || this.default_path();
      this.image = this.g.append("path");
      this.set_path();
    }

    Polygon.prototype.default_path = function() {
      var invsqrt3;
      invsqrt3 = 1 / Math.sqrt(3);
      return [
        {
          pathSegTypeAsLetter: 'M',
          x: -this.size,
          y: this.size * invsqrt3,
          react: true
        }, {
          pathSegTypeAsLetter: 'L',
          x: 0,
          y: -2 * this.size * invsqrt3,
          react: true
        }, {
          pathSegTypeAsLetter: 'L',
          x: this.size,
          y: this.size * invsqrt3,
          react: true
        }, {
          pathSegTypeAsLetter: 'Z'
        }
      ];
    };

    Polygon.prototype.d = function() {
      return Utils.d(this.path);
    };

    Polygon.prototype.polygon_path = function() {
      var i, _i, _ref;
      for (i = _i = 0, _ref = this.path.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        if (this.path[i].pathSegTypeAsLetter === 'Z' || this.path[i].pathSegTypeAsLetter === 'z') {
          continue;
        }
        this.path[i].r = new Vec(this.path[i]).subtract(this.path[i + 1 % this.path.length - 1]);
        this.path[i].n = new Vec({
          x: -this.path[i].y,
          y: this.path[i].x
        }).normalize();
      }
    };

    Polygon.prototype.set_path = function(path) {
      this.path = path != null ? path : this.path;
      this.pathref = this.path.map(function(d) {
        return _.clone(d);
      });
      this.polygon_path();
      this.maxnode = new Vec(_.max(this.path, function(node) {
        return node.d = node.x * node.x + node.y * node.y;
      }));
      this.size = this.maxnode.length();
      this.pathBB();
      return this.image.attr("d", this.d());
    };

    Polygon.prototype.pathBB = function() {
      this.pathwidth = _.max(this.path, function(node) {
        return node.x;
      }).x - _.min(this.path, function(node) {
        return node.x;
      }).x;
      return this.pathheight = _.max(this.path, function(node) {
        return node.y;
      }).y - _.min(this.path, function(node) {
        return node.y;
      }).y;
    };

    Polygon.prototype.rotate_path = function() {
      var c, i, s, seg, _i, _ref;
      for (i = _i = 0, _ref = this.path.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        seg = this.path[i];
        if (seg.x == null) {
          continue;
        }
        c = Math.cos(this.angle);
        s = Math.sin(this.angle);
        seg.x = c * this.pathref[i].x - s * this.pathref[i].y;
        seg.y = s * this.pathref[i].x + c * this.pathref[i].y;
      }
      this.polygon_path();
    };

    return Polygon;

  })(Element);

  this.Collision = (function() {
    var circle_circle_dist, circle_lineseg_dist, lineseg_intersect, z_check;

    function Collision() {}

    Collision.lastquad = Utils.timestamp();

    Collision.quadwait = 33 + 1 / 3;

    Collision.list = [];

    Collision.update_quadtree = function(force_update) {
      var data, timestamp;
      if (force_update == null) {
        force_update = false;
      }
      if (!(this.list.length > 0)) {
        return;
      }
      timestamp = Utils.timestamp();
      if (force_update || timestamp - this.lastquad > this.quadwait || (this.quadtree == null)) {
        data = this.list.map(function(d) {
          return {
            x: d.r.x,
            y: d.r.y,
            d: d
          };
        });
        this.quadtree = d3.geom.quadtree(data);
        return this.lastquad = timestamp;
      }
    };

    Collision.quadtree = Collision.update_quadtree();

    Collision.check = function(ei, ej) {
      var d, m, n, name, sort;
      name = [ei.type, ej.type];
      sort = [ei.type, ej.type].sort();
      if (name[0] === sort[0] && name[1] === sort[1]) {
        m = ei;
        n = ej;
      } else {
        m = ej;
        n = ei;
      }
      switch (m.type) {
        case 'Circle':
          switch (n.type) {
            case 'Circle':
              d = this.circle_circle(m, n);
              if (d.collision) {
                Reaction.circle_circle(m, n, d);
              }
              break;
            case 'Polygon':
              d = this.circle_polygon(m, n);
              if (d.collision) {
                Reaction.circle_polygon(m, n, d);
              }
          }
          break;
        case 'Polygon':
          switch (n.type) {
            case 'Polygon':
              d = this.polygon_polygon(m, n);
              if (d.collision) {
                Reaction.polygon_polygon(m, n, d);
              }
          }
      }
    };

    Collision.circle_circle = function(m, n) {
      var d;
      d = circle_circle_dist(m, n);
      d.collision = d.dist <= d.dmin ? true : false;
      return d;
    };

    Collision.circle_polygon = function(circle, polygon) {
      var d, i, _i, _ref;
      for (i = _i = 0, _ref = polygon.path.length - 2; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        if (!polygon.path[i].react) {
          continue;
        }
        d = circle_lineseg_dist(circle, polygon, i);
        if (d.dist > circle.size) {
          continue;
        }
        d.collision = true;
        break;
      }
      return d;
    };

    Collision.polygon_polygon = function(m, n) {
      var d, i, j, _i, _j, _ref, _ref1;
      d = new Vec(m.r).subtract(n.r);
      d.dist = d.length();
      d.collision = false;
      d.dmin = m.size + n.size;
      if (d.dist <= d.dmin) {
        for (i = _i = 0, _ref = m.path.length - 2; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
          for (j = _j = 0, _ref1 = n.path.length - 2; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; j = 0 <= _ref1 ? ++_j : --_j) {
            if (!lineseg_intersect(m, n, i, j)) {
              continue;
            }
            d.i = i;
            d.j = j;
            d.collision = true;
            break;
          }
          if (d.collision) {
            break;
          }
        }
      }
      return d;
    };

    circle_circle_dist = function(m, n) {
      var d;
      d = new Vec(m.r).subtract(n.r);
      d.dist = d.length();
      d.dmin = m.size + n.size;
      return d;
    };

    circle_lineseg_dist = function(circle, polygon, i) {
      var d, dr, r, ri, rj, rr, t, tr;
      ri = polygon.path[i];
      rj = z_check(polygon.path, i);
      r = new Vec(rj).subtract(ri);
      rr = r.length2();
      dr = new Vec(circle.r).subtract(ri).subtract(polygon.r);
      t = r.dot(dr) / rr;
      if (t < 0) {

      } else if (t > 1) {
        dr = new Vec(circle.r).subtract(rj).subtract(polygon.r);
      } else {
        tr = new Vec(r).scale(t).add(ri).add(polygon.r);
        dr = new Vec(circle.r).subtract(tr);
      }
      return d = {
        t: t,
        x: dr.x,
        y: dr.y,
        r: [r.x, r.y],
        rr: rr,
        dist: dr.length()
      };
    };

    lineseg_intersect = function(m, n, i, j) {
      var A1, A2, B1, B2, C1, C2, check1, check2, check3, check4, det, ri, rj, si, sj, x, y, _ref, _ref1, _ref2, _ref3;
      ri = new Vec(m.path[i]);
      rj = new Vec(z_check(m.path, i));
      si = new Vec(n.path[j]);
      sj = new Vec(z_check(n.path, j));
      A1 = rj.y - ri.y;
      B1 = ri.x - rj.x;
      C1 = A1 * (ri.x + m.r.x) + B1 * (ri.y + m.r.y);
      A2 = sj.y - si.y;
      B2 = si.x - sj.x;
      C2 = A2 * (si.x + n.r.x) + B2 * (si.y + n.r.y);
      det = A1 * B2 - A2 * B1;
      if (det === 0) {
        return false;
      }
      x = (B2 * C1 - B1 * C2) / det;
      y = (A1 * C2 - A2 * C1) / det;
      check1 = (Math.min(ri.x, rj.x) - m.tol <= (_ref = x - m.r.x) && _ref <= Math.max(ri.x, rj.x) + m.tol);
      check2 = (Math.min(si.x, sj.x) - n.tol <= (_ref1 = x - n.r.x) && _ref1 <= Math.max(si.x, sj.x) + n.tol);
      check3 = (Math.min(ri.y, rj.y) - m.tol <= (_ref2 = y - m.r.y) && _ref2 <= Math.max(ri.y, rj.y) + m.tol);
      check4 = (Math.min(si.y, sj.y) - n.tol <= (_ref3 = y - n.r.y) && _ref3 <= Math.max(si.y, sj.y) + n.tol);
      if (check1 && check2 && check3 && check4) {
        return true;
      } else {
        return false;
      }
    };

    z_check = function(seg, i) {
      switch (seg[i + 1].pathSegTypeAsLetter) {
        case 'z':
        case 'Z':
          return seg[0];
        default:
          return seg[i + 1];
      }
    };

    return Collision;

  })();

  this.Reaction = (function() {
    var elastic_collision;

    function Reaction() {}

    Reaction.circle_circle = function(m, n, d) {
      var line, shift;
      if (m.death_check(n) || n.death_check(m)) {
        return;
      }
      line = new Vec(d);
      line.x = line.x / d.dist;
      line.y = line.y / d.dist;
      shift = (d.dmin + Math.max(m.tol, n.tol) - d.dist) * 0.5;
      elastic_collision(m, n, line, shift);
      m.reaction(n);
    };

    Reaction.circle_polygon = function(circle, polygon, d) {
      if (circle.death_check(polygon) || polygon.death_check(circle)) {
        return;
      }
      console.log('Reaction.circle_polygon not implemented yet');
    };

    Reaction.polygon_polygon = function(m, n, d) {
      var dot1, dot2, mseg, normal, nseg, shift;
      if (m.death_check(n) || n.death_check(m)) {
        return;
      }
      mseg = m.path[d.i];
      nseg = n.path[d.j];
      dot1 = mseg.n.dot(d);
      dot2 = nseg.n.dot(d);
      normal = Math.abs(dot1) > Math.abs(dot2) ? new Vec(mseg.n).scale(dot1 / Math.abs(dot1)) : new Vec(nseg.n).scale(dot2 / Math.abs(dot2));
      shift = 0.5 * Math.max(m.tol, n.tol);
      elastic_collision(m, n, normal, shift);
      m.reaction(n);
    };

    elastic_collision = function(m, n, line, shift) {
      var cPar, dPar, lshift, uPar, uPerp, vPar, vPerp;
      lshift = new Vec(line).scale(shift);
      m.r = m.r.add(lshift);
      n.r = n.r.subtract(lshift);
      cPar = m.v.dot(line);
      vPar = new Vec(line).scale(cPar);
      vPerp = new Vec(m.v).subtract(vPar);
      dPar = n.v.dot(line);
      uPar = new Vec(line).scale(dPar);
      uPerp = new Vec(n.v).subtract(uPar);
      m.v = uPar.add(vPerp);
      n.v = vPar.add(uPerp);
    };

    return Reaction;

  })();

  this.Force = (function() {

    function Force(params) {
      this.params = params != null ? params : {
        type: 'constant',
        fx: 0,
        fy: 0
      };
    }

    Force.prototype.f = function(r) {
      var dr, fx, fy, r2, r3;
      switch (this.params.type) {
        case 'constant':
          fx = this.params.x;
          fy = this.params.y;
          break;
        case 'spring':
          fx = -(r.x - this.params.cx);
          fy = -(r.y - this.params.cy);
          break;
        case 'charge':
        case 'gravity':
          dr = new Vec({
            x: this.params.cx - r.x,
            y: this.params.cy - r.y
          });
          r2 = dr.length2();
          r3 = r2 * Math.sqrt(r2);
          fx = this.params.q * dr.x / r3;
          fy = this.params.q * dr.y / r3;
          break;
        case 'random':
          fx = 2 * (Math.random() - 0.5) * this.params.xScale;
          fy = 2 * (Math.random() - 0.5) * this.params.yScale;
          if (r.x > this.params.xBound) {
            fx = -this.params.fxBound;
          }
          if (r.y > this.params.yBound) {
            fy = -this.params.fyBound;
          }
          if (r.x < 0) {
            fx = this.params.fxBound;
          }
          if (r.y < 0) {
            fy = this.params.fyBound;
          }
      }
      return new Vec({
        x: fx,
        y: fy
      });
    };

    return Force;

  })();

  this.Vec = (function() {

    function Vec(config) {
      this.config = config != null ? config : {};
      this.x = this.config.x || 0;
      this.y = this.config.y || 0;
    }

    Vec.prototype.scale = function(c) {
      this.x *= c;
      this.y *= c;
      return this;
    };

    Vec.prototype.add = function(v) {
      this.x += v.x;
      this.y += v.y;
      return this;
    };

    Vec.prototype.subtract = function(v) {
      this.x -= v.x;
      this.y -= v.y;
      return this;
    };

    Vec.prototype.rotate = function(a) {
      var c, s, _ref;
      c = Math.cos(a);
      s = Math.sin(a);
      return _ref = [c * this.x - s * this.y, this.y = s * this.x + c * this.y], this.x = _ref[0], this.y = _ref[1], _ref;
    };

    Vec.prototype.dot = function(v) {
      return this.x * v.x + this.y * v.y;
    };

    Vec.prototype.length2 = function() {
      return this.dot(this);
    };

    Vec.prototype.length = function() {
      return Math.sqrt(this.length2());
    };

    Vec.prototype.normalize = function() {
      var inverseLength;
      inverseLength = 1 / this.length();
      this.x *= inverseLength;
      this.y *= inverseLength;
      return this;
    };

    Vec.prototype.dist2 = function(v) {
      return new Vec(this).subtract(v).length2();
    };

    Vec.prototype.dist = function(v) {
      return Math.sqrt(this.dist2(v));
    };

    return Vec;

  })();

  this.Ship = (function() {

    function Ship() {}

    Ship.viper = function() {
      return {
        path: [
          {
            pathSegTypeAsLetter: 'M',
            x: 0,
            y: -24,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: 24,
            y: 38,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: 9,
            y: 58,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: 3,
            y: 48,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: -3,
            y: 48,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: -9,
            y: 58,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: -24,
            y: 38,
            react: true
          }, {
            pathSegTypeAsLetter: 'Z'
          }
        ],
        url: GameAssetsUrl + "viper_1.png",
        offset: {
          x: 0,
          y: 19
        },
        bullet_stroke: 'none',
        bullet_fill: '#fff',
        bullet_size: 2,
        bullet_speed: 15,
        bullet_tick: 25
      };
    };

    Ship.fang = function() {
      return {
        path: [
          {
            pathSegTypeAsLetter: 'M',
            x: 10,
            y: -20,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: 30,
            y: -10,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: 40,
            y: 20,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: 30,
            y: 50,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: 15,
            y: 60,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: 10,
            y: 67,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: 5,
            y: 70,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: -5,
            y: 70,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: -10,
            y: 67,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: -15,
            y: 60,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: -30,
            y: 50,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: -40,
            y: 20,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: -30,
            y: -10,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: -10,
            y: -20,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: -5,
            y: 40,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: 5,
            y: 40,
            react: true
          }, {
            pathSegTypeAsLetter: 'Z',
            react: true
          }
        ],
        url: GameAssetsUrl + "fang_1.png",
        offset: {
          x: 0,
          y: 25
        },
        bullet_stroke: '#fff',
        bullet_fill: 'none',
        bullet_size: 5,
        bullet_speed: 10,
        bullet_tick: 40
      };
    };

    Ship.sidewinder = function() {
      return {
        path: [
          {
            pathSegTypeAsLetter: 'M',
            x: 8,
            y: -26,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: 32,
            y: -14,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: 44,
            y: 18,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: 32,
            y: 26,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: 30,
            y: 18,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: -28,
            y: 18,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: -32,
            y: 26,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: -44,
            y: 18,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: -32,
            y: -14,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: -8,
            y: -26,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: -8,
            y: -14,
            react: true
          }, {
            pathSegTypeAsLetter: 'L',
            x: 8,
            y: -14,
            react: true
          }, {
            pathSegTypeAsLetter: 'Z'
          }
        ],
        url: GameAssetsUrl + "sidewinder_1.png",
        offset: {
          x: 0,
          y: 0
        },
        bullet_stroke: 'none',
        bullet_fill: '#000',
        bullet_size: 4,
        bullet_speed: 10,
        bullet_tick: 30
      };
    };

    return Ship;

  })();

  this.Bullet = (function(_super) {

    __extends(Bullet, _super);

    function Bullet(config) {
      this.config = config != null ? config : {};
      Bullet.__super__.constructor.apply(this, arguments);
      this.is_bullet = true;
      this.size = 3;
      this.fill("#000");
    }

    Bullet.prototype.death_check = function(n) {
      if (n.is_root) {
        return true;
      }
      this.death();
      n.death();
      Gamescore.increment_value();
      if (typeof Gameprez !== "undefined" && Gameprez !== null) {
        Gameprez.score(Gamescore.value);
      }
      return true;
    };

    return Bullet;

  })(Circle);

  this.Drone = (function(_super) {

    __extends(Drone, _super);

    function Drone(config) {
      this.config = config != null ? config : {};
      Drone.__super__.constructor.apply(this, arguments);
      this.image.remove();
      this.image = this.g.append("image").attr("xlink:href", GameAssetsUrl + "drone_1.png").attr("x", -this.size).attr("y", -this.size).attr("width", this.size * 2).attr("height", this.size * 2);
      this.react = false;
    }

    Drone.prototype.death = function() {
      var N, dur, fill;
      this.deactivate();
      dur = 100;
      N = 320;
      fill = "hsl(" + Math.random() * N + ", 50%, 70%)";
      this.g.append("circle").attr("r", this.size).attr("x", 0).attr("y", 0).transition().duration(dur).ease('sqrt').attr("fill", fill).remove();
      return this.g.attr("class", "").transition().delay(dur).duration(dur * 2).ease('sqrt').style("opacity", "0").remove();
    };

    Drone.prototype.draw = function() {
      this.angle = -Math.atan2(this.f.x, this.f.y);
      return Drone.__super__.draw.apply(this, arguments);
    };

    return Drone;

  })(Circle);

  this.Dronewar = (function(_super) {

    __extends(Dronewar, _super);

    function Dronewar() {
      var _this = this;
      this.reset = function() {
        return Dronewar.prototype.reset.apply(_this, arguments);
      };
      this.progress = function() {
        return Dronewar.prototype.progress.apply(_this, arguments);
      };
      this.keydown = function() {
        return Dronewar.prototype.keydown.apply(_this, arguments);
      };
      Dronewar.__super__.constructor.apply(this, arguments);
      this.initialN = this.config.initialN || 5;
      this.N = this.initialN;
      this.root = new Root();
      this.scoretxt = this.g.append("text").text("").attr("stroke", "none").attr("fill", "white").attr("font-size", "18").attr("x", "20").attr("y", "40").attr('font-family', 'arial black');
      this.lives = this.g.append("text").text("").attr("stroke", "none").attr("fill", "white").attr("font-size", "18").attr("x", "20").attr("y", "20").attr('font-family', 'arial black');
      this.leveltxt = this.g.append("text").text("").attr("stroke", "none").attr("fill", "white").attr("font-size", "18").attr("x", "20").attr("y", "60").attr('font-family', 'arial black');
      d3.select(window).on("keydown", this.keydown);
    }

    Dronewar.prototype.level = function() {
      var d, dur, dx, dy, element, i, j, k, n, newAttacker, speed, _i, _j, _k, _l, _len, _ref, _ref1, _ref2, _ref3;
      this.svg.style("cursor", "none");
      dur = 600;
      d3.select('#game_div').transition(dur).style("background-color", function() {
        return "hsl(" + Math.random() * 360 + ", 15%, 20%)";
      });
      this.element = [];
      for (i = _i = 0, _ref = this.N - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        newAttacker = new Drone();
        newAttacker.g.attr("class", "attacker");
        this.element.push(newAttacker);
      }
      for (k = _j = 0, _ref1 = Math.ceil(Math.sqrt(this.element.length)); 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; k = 0 <= _ref1 ? ++_j : --_j) {
        for (j = _k = 0, _ref2 = Math.ceil(Math.sqrt(this.element.length)); 0 <= _ref2 ? _k <= _ref2 : _k >= _ref2; j = 0 <= _ref2 ? ++_k : --_k) {
          i = k * Math.floor(Math.sqrt(this.element.length)) + j;
          if (i > this.element.length - 1) {
            break;
          }
          this.element[i].r.x = this.width * 0.5 + k * this.element[i].size * 2 + this.element[i].tol - Math.ceil(Math.sqrt(this.element.length)) * this.element[i].size;
          this.element[i].r.y = this.height * 0.1 + j * this.element[i].size * 2 + this.element[i].tol;
          speed = 20;
          dx = this.root.r.x - this.element[i].r.x;
          dy = this.root.r.y - this.element[i].r.y;
          d = Math.sqrt(dx * dx + dy * dy);
          dx /= d;
          dy /= d;
          this.element[i].v.x = 0.1 * this.N * dx;
          this.element[i].v.y = 0.1 * this.N * dy;
        }
      }
      _ref3 = this.element;
      for (_l = 0, _len = _ref3.length; _l < _len; _l++) {
        element = _ref3[_l];
        element.draw();
      }
      this.root.attacker = this.element;
      this.root.update_attacker();
      this.root.start();
      dur = 400;
      n = this.element.length * 2;
      d3.selectAll(".attacker").data(this.element).style("opacity", 0).transition().delay(function(d, i) {
        return i / n * dur;
      }).duration(dur).style("opacity", 1).each("end", function(d, i) {
        return d.activate();
      });
      this.element.push(this.root);
      return this.init();
    };

    Dronewar.prototype.keydown = function() {
      switch (d3.event.keyCode) {
        case 39:
          this.root.angle += this.root.angleStep;
          this.root.draw([this.root.r.x, this.root.r.y]);
          break;
        case 37:
          this.root.angle -= this.root.angleStep;
          this.root.draw([this.root.r.x, this.root.r.y]);
          break;
        case 40:
        case 38:
          this.root.angle += Math.PI;
          this.root.draw([this.root.r.x, this.root.r.y]);
          break;
        case 82:
          if (Gamescore.lives < 0) {
            this.reset();
          }
      }
    };

    Dronewar.prototype.stop = function() {
      Dronewar.__super__.stop.apply(this, arguments);
      this.root.stop();
      if (typeof Gameprez !== "undefined" && Gameprez !== null) {
        return Gameprez.end(Gamescore.value);
      }
    };

    Dronewar.prototype.start = function() {
      var dur, fang, go, how, prompt, root, sidewinder, title, viper,
        _this = this;
      if (typeof Gameprez !== "undefined" && Gameprez !== null) {
        Gameprez.start();
      }
      this.root.draw();
      title = this.g.append("text").text("").attr("stroke", "none").attr("fill", "white").attr("font-size", "48").attr("x", this.width / 2 - 320).attr("y", 90).attr('font-family', 'arial').attr('font-weight', 'bold');
      title.text("DRONEWAR");
      prompt = this.g.append("text").text("").attr("stroke", "none").attr("fill", "white").attr("font-size", "36").attr("x", this.width / 2 - 320).attr("y", this.height / 4 + 40).attr('font-family', 'arial').attr('font-weight', 'bold');
      prompt.text("SELECT SHIP");
      root = this.root;
      sidewinder = this.g.append("text").text("").attr("stroke", "none").attr("fill", "white").attr("font-size", "24").attr("x", this.width / 2 - 320).attr("y", this.height / 4 + 80).attr('font-family', 'arial').attr('font-weight', 'bold').style("cursor", "pointer");
      sidewinder.text("SIDEWINDER").style("fill", "#006");
      dur = 500;
      sidewinder.on("click", function() {
        if (this.style.fill === '#000066') {
          return;
        }
        root.ship(Ship.sidewinder());
        d3.select(this).transition().duration(dur).style("fill", "#006");
        viper.style("fill", "#FFF");
        return fang.style("fill", "#FFF");
      });
      viper = this.g.append("text").text("").attr("stroke", "none").attr("fill", "white").attr("font-size", "24").attr("x", this.width / 2 - 320).attr("y", this.height / 4 + 110).attr('font-family', 'arial').attr('font-weight', 'bold').style("cursor", "pointer");
      viper.text("VIPER");
      viper.on("click", function() {
        if (this.style.fill === '#000066') {
          return;
        }
        root.ship(Ship.viper());
        d3.select(this).transition().duration(dur).style("fill", "#006");
        sidewinder.style("fill", "#FFF");
        return fang.style("fill", "#FFF");
      });
      fang = this.g.append("text").text("").attr("stroke", "none").attr("fill", "white").attr("font-size", "24").attr("x", this.width / 2 - 320).attr("y", this.height / 4 + 140).attr('font-family', 'arial').attr('font-weight', 'bold').style("cursor", "pointer");
      fang.text("FANG");
      fang.on("click", function() {
        if (this.style.fill === '#000066') {
          return;
        }
        root.ship(Ship.fang());
        d3.select(this).transition().duration(dur).style("fill", "#006");
        viper.style("fill", "#FFF");
        return sidewinder.style("fill", "#FFF");
      });
      go = this.g.append("text").text("").attr("stroke", "none").attr("fill", "#FF2").attr("font-size", "36").attr("x", this.root.r.x - 60).attr("y", this.root.r.y + 100).attr('font-family', 'arial').attr('font-weight', 'bold').style("cursor", "pointer");
      go.text("START");
      go.on("click", function() {
        dur = 500;
        title.transition().duration(dur).style("opacity", 0).remove();
        prompt.transition().duration(dur).style("opacity", 0).remove();
        sidewinder.transition().duration(dur).style("opacity", 0).remove();
        viper.transition().duration(dur).style("opacity", 0).remove();
        fang.transition().duration(dur).style("opacity", 0).remove();
        go.transition().duration(dur).style("opacity", 0).remove();
        how.transition().duration(dur).style("opacity", 0).remove();
        return d3.timer(_this.progress);
      });
      how = this.g.append("text").text("").attr("stroke", "none").attr("fill", "white").attr("font-size", "18").attr("x", this.width / 2 - 320).attr("y", this.root.r.y + 130).attr('font-family', 'arial').attr('font-weight', 'bold').style("cursor", "pointer");
      return how.text("Use the mouse for controlling movement, scrollwheel for rotation");
    };

    Dronewar.prototype.progress = function() {
      var dur, inactive;
      this.scoretxt.text('SCORE: ' + Gamescore.value);
      this.leveltxt.text('LEVEL: ' + (this.N - this.initialN + 1));
      if (Gamescore.lives >= 0) {
        this.lives.text('LIVES: ' + Gamescore.lives);
      } else {
        dur = 420;
        this.root.game_over();
        this.lives.text("GAME OVER, PRESS 'R' TO RESTART");
        this.stop();
        return true;
      }
      inactive = this.element.every(function(element) {
        return element.is_root || (element.react === false && element.fixed === true);
      });
      if (inactive) {
        this.N++;
        this.charge *= 10;
        this.level();
      }
    };

    Dronewar.prototype.reset = function() {
      this.g.selectAll("g").remove();
      this.lives.text("");
      this.scoretxt.text("");
      this.leveltxt.text("");
      this.svg.style("cursor", "auto");
      this.N = this.initialN;
      Gamescore.value = 0;
      this.root = new Root();
      Gamescore.lives = Gamescore.initialLives;
      return this.start();
    };

    return Dronewar;

  })(Game);

  this.Root = (function(_super) {

    __extends(Root, _super);

    function Root(config) {
      var _this = this;
      this.config = config != null ? config : {
        size: 0
      };
      this.fire = function() {
        return Root.prototype.fire.apply(_this, arguments);
      };
      this.spin = function() {
        return Root.prototype.spin.apply(_this, arguments);
      };
      this.update = function(xy) {
        if (xy == null) {
          xy = d3.mouse(_this.svg.node());
        }
        return Root.prototype.update.apply(_this, arguments);
      };
      Root.__super__.constructor.call(this, this.config);
      this.is_root = true;
      this.fixed = true;
      this.r.x = this.width / 2;
      this.r.y = this.height - 180;
      this.angleStep = 2 * Math.PI / 60;
      this.lastfire = Utils.timestamp();
      this.attacker = [];
      this.charge = 5e4;
      this.stroke("none");
      this.fill("#000");
      this.bitmap = this.g.insert("image", 'path').attr('id', 'ship_image');
      this.ship();
    }

    Root.prototype.update = function(xy) {
      if (xy == null) {
        xy = d3.mouse(this.svg.node());
      }
      if (!this.react) {
        return;
      }
      this.r.x = xy[0];
      this.r.y = xy[1];
      this.draw();
      this.collision_detect();
      if (this.attacker != null) {
        return this.update_attacker();
      }
    };

    Root.prototype.spin = function() {
      var delta;
      delta = this.angleStep * d3.event.wheelDelta / Math.abs(d3.event.wheelDelta);
      this.angle = this.angle - delta;
      this.rotate_path();
      return this.draw();
    };

    Root.prototype.fire = function() {
      var bullet, timestamp, x, y;
      timestamp = Utils.timestamp();
      if (!(this.go && timestamp - this.lastfire > this.wait)) {
        return;
      }
      this.lastfire = timestamp;
      bullet = new Bullet();
      bullet.size = this.bullet_size;
      x = Math.cos(this.angle - Math.PI * 0.5);
      y = Math.sin(this.angle - Math.PI * 0.5);
      bullet.r.x = this.r.x + x * (this.size / 3 + bullet.size);
      bullet.r.y = this.r.y + y * (this.size / 6);
      bullet.v.x = this.bullet_speed * x;
      bullet.v.y = this.bullet_speed * y;
      bullet.stroke(this.bullet_stroke);
      bullet.fill(this.bullet_fill);
      bullet.quadtree = this.quadtree;
      bullet.start();
    };

    Root.prototype.update_attacker = function() {
      var attacker, _i, _len, _ref, _results;
      if (!(this.attacker.length > 0)) {
        return;
      }
      this.params = {
        type: 'charge',
        cx: this.r.x,
        cy: this.r.y,
        q: this.charge
      };
      _ref = this.attacker;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        attacker = _ref[_i];
        _results.push(attacker.force.params = this.params);
      }
      return _results;
    };

    Root.prototype.activate = function() {
      this.react = true;
      return this.start();
    };

    Root.prototype.ship = function(ship, dur) {
      var endPath,
        _this = this;
      if (ship == null) {
        ship = Ship.sidewinder();
      }
      if (dur == null) {
        dur = 500;
      }
      this.go = false;
      this.bullet_stroke = ship.bullet_stroke;
      this.bullet_fill = ship.bullet_fill;
      this.bullet_size = ship.bullet_size;
      this.bullet_speed = ship.bullet_speed / this.dt;
      this.wait = ship.bullet_tick;
      this.path = ship.path;
      console.log(this.wait);
      this.pathBB();
      endPath = this.d();
      this.bitmap.attr('opacity', 1).transition().duration(dur * 0.5).attr('opacity', 0).remove();
      this.image.attr("opacity", 1).data([endPath]).transition().duration(dur).attrTween("d", Utils.pathTween).transition().duration(dur * 0.5).attr("opacity", 0);
      return this.bitmap.attr("xlink:href", ship.url).attr("x", -this.pathwidth * 0.5 + ship.offset.x).attr("y", -this.pathheight * 0.5 + ship.offset.y).attr("width", this.pathwidth).attr("height", this.pathheight).attr("opacity", 0).transition().delay(dur).duration(dur).attr("opacity", 1).each('end', function() {
        _this.set_path();
        _this.go = true;
        return d3.timer(_this.fire);
      });
    };

    Root.prototype.start = function() {
      Root.__super__.start.apply(this, arguments);
      this.svg.on("mousemove", this.update);
      this.svg.on("mousedown", this.fire);
      return this.svg.on("mousewheel", this.spin);
    };

    Root.prototype.stop = function() {
      Root.__super__.stop.apply(this, arguments);
      this.svg.on("mousemove", null);
      this.svg.on("mousedown", null);
      return this.svg.on("mousewheel", null);
    };

    Root.prototype.death_check = function(n) {
      if (n.is_bullet) {
        return true;
      }
      n.death();
      this.death();
      Gamescore.lives -= 1;
      return true;
    };

    Root.prototype.death = function() {
      var N, dur, fill;
      N = 240;
      fill = '#ff0';
      dur = 120;
      return this.image.transition().duration(dur / 5).attr('opacity', 1).transition().duration(dur).ease('sqrt').attr("fill", fill).transition().duration(dur).ease('linear').attr("fill", this.fill()).transition().duration(dur / 5).attr('opacity', 0);
    };

    Root.prototype.game_over = function(dur) {
      if (dur == null) {
        dur = 500;
      }
      this.image.transition().duration(dur / 5).attr('opacity', 1).transition().duration(dur).attr("fill", "#900").transition().duration(dur * 0.25).ease('sqrt').style("opacity", 0);
      return this.bitmap.transition().duration(dur).attr('opacity', 0);
    };

    return Root;

  })(Polygon);

}).call(this);
